sudo: required
dist: trusty

language: node_js

node_js:
  - "10"

before_script: 
  - touch foreyesConfig/foreyes.config.js

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  - yarn install:token
  - yarn semantic-release